/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./worker-configuration.d.ts` (hash: bb4750fd7e76d79a8db586025a444867)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	ASSETS: Fetcher;
	WORKOS_CLIENT_ID: string;
	WORKOS_API_KEY: string;
	WORKOS_REDIRECT_URI: string;
	WORKOS_COOKIE_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORKOS_CLIENT_ID" | "WORKOS_API_KEY" | "WORKOS_REDIRECT_URI" | "WORKOS_COOKIE_PASSWORD">> {}
}
